### ISSUE TITLE
Change the way lib size is described?

### ISSUE THREAD

**Issue by pearofducks** [pshihn/rough-notation#23]
Congrats on publishing the library!

I'd just like to suggest an edit to the site/README.

> Rough Notation is about 3.2kb in size when gzipped

This feels kinda "marketing-ish" to me, when there's a 27k (min'd) dependency coming with it.

**Comment by pshihn** [comment]
It actually is 3.2kb,  3.4k as an IIfe with latest changes. 
The issue here is that the dependencies of the project should be specified as dev-dependencies. They are not loaded by the built/shipped module. 

e.g. look at the network tab of roughnotation.com

<img width="604" alt="Screen Shot 2020-05-31 at 8 36 18 PM" src="https://user-images.githubusercontent.com/833927/83373868-b7053500-a37e-11ea-9c31-08a37b55ab58.png">

**Comment by pshihn** [comment]
Dependency fixed in https://github.com/pshihn/rough-notation/pull/24
Bundlephobia:  https://bundlephobia.com/result?p=rough-notation@0.2.2

**Comment by pearofducks** [comment]
That's awesome! Thanks for clarifying. :D
