### ISSUE TITLE
animationDelay taken away from RoughAnnotationConfigBase ?

### ISSUE THREAD

**Issue by mikyaj** [pshihn/rough-notation#43]
I noticed that `animationDelay` has been taken away fron [config](https://github.com/pshihn/rough-notation/blob/master/src/model.ts#L21) object. Any particular reason for that ?  README might need an updated in that case.

**Comment by pshihn** [comment]
The reason was that users can call `show` when they want on the annotation. Adding the artificial delay didn't seem essential to the core of the lib. If the caller wants to. delay the animation, they can call it after that interval. 
For chaining animations, animationgroup already provides that. 

Still a pre 1.0 release so hoping to hash out the lightest API 

You're correct I may have missed updating readme.

**Comment by pshihn** [comment]
Readme updated https://github.com/pshihn/rough-notation/commit/e1d7e1b930dde4fa26455918712a35d5daf901f6
